version: '3.8'

services:
  api:
    build: .
    container_name: blog-api
    ports:
      - '3000:3000' 
    depends_on:
      - mongo 
    env_file:
      - .env
    volumes:
      - .:/app 
    restart: unless-stopped

  
  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - '27017:27017' 
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

volumes:
  mongo-data: 